### ISSUE TITLE
Add diagram

### ISSUE THREAD

**Issue by stephlocke** [r-hub/docs#1]
An architecture diagram would really help people understand how this hangs together. I've drafted one in mermaid as a starting point based on my understanding from the docs.

[Mermaid JSFiddle](http://knsv.github.io/mermaid/live_editor/#/edit/c2VxdWVuY2VEaWFncmFtCkZyb250RW5kLT4-IFJhYmJpdE1ROiBRdWVyeQpOb3RlIHJpZ2h0IG9mIEZyb250RW5kOiBkb2trdS1yYWJiaXRtcQpSYWJiaXRNUS0-PiBCYWNrRW5kOiBGb3J3YXJkIHF1ZXJ5CkJhY2tFbmQtPj4gSmVua2luczogQ3JlYXRlIGpvYgpOb3RlIHJpZ2h0IG9mIEJhY2tFbmQ6IGRva2t1LWplbmtpbnMKSmVua2lucy0-PkJ1aWxkZXI6IEJ1aWxkIGpvYgpOb3RlIHJpZ2h0IG9mIEplbmtpbnM6IHN3YXJtIHBsdWdpbgpCdWlsZGVyLT4-SmVua2luczogQnVpbGQgcmVzdWx0CkplbmtpbnMtPj5CYWNrRW5kOiBKb2IgcmVzdWx0CkJhY2tFbmQtPj4gUmFiYml0TVE6IFJlc3BvbnNlClJhYmJpdE1RLT4-IEZyb250RW5kOiBGb3J3YXJkIHJlc3BvbnNlCkZyb250RW5kLT4gSmVua2luczogQ2VudHJhbCBWTQ)

**Comment by gaborcsardi** [comment]
Well, sorry for the _late_ response. There is a diagram now, e.g. from a recent presentation: https://github.com/r-hub/presentations/blob/master/2016-09-14-earl/r-hub.svg
