### ISSUE TITLE
rhub::check_for_cran() vs devtools::check_rhub()

### ISSUE THREAD

**Issue by maelle** [r-hub/docs#2]
`devtools::check_rhub()` allows to pass arguments to `pkgbuild::build()` before uploading the package to R-hub builder.

**Comment by maelle** [comment]
An example of when this could be used would be good.

**Comment by gaborcsardi** [comment]
I don't think this is important, you can call `build()` or `R CMD build` first and then `rhub::check()` on the tarball.

**Comment by maelle** [comment]
or you could directly run `rhub::check()`, I know, but keeping notes here in case someone ever asks. :-)

**Comment by maelle** [comment]
Another difference, if folks have `devtools` automatically loaded for interactive work (because of https://usethis.r-lib.org/articles/articles/usethis-setup.html#use-usethis-in-interactive-work + `usethis::use_devtools()`) then they have less characters to type. :grin:

**Comment by maelle** [comment]
Other thing.

https://twitter.com/ma_salmon/status/1133421395499802625

Not sure if the topic is worth a docs topic / blog post (what's your R-hub workflow? with answers from a few package devs) but keeping track here.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now.
