### ISSUE TITLE
More guidance about System Requirements

### ISSUE THREAD

**Issue by maelle** [r-hub/docs#3]
* Explain how system dependencies are installed on the different platforms. On some platforms, if something is missing, you won't be able to do anything about it yourself but will need to open an issue.

* Explain how to check a package's `SystemRequirements` field is parsed. Recommend to locally use `sysreqs` to check that for one's package?

Part of this in the docs, maybe another part in a blog post.

**Comment by maelle** [comment]
Mention fonts/TeX stuff explicitely.

**Comment by maelle** [comment]
For that to happen, the official guidance about fonts/TeX would need to be clearer. Note that there are less fonts issues nowadays, but tex installation remains present in issues.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now.
